version: '3.7'
services:
  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=somuga
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    restart: on-failure
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/somuga?autoReconnect=true&useSSL=false
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mysql-db